# : Manager [[[

[mgr]
cwd = { fg = "#e1e2e9" }

# Tab
tab_active = { fg = "#02315f", bg = "#a6c8ff", bold = true }
tab_inactive = { fg = "#234776", bg = "#d5e3ff" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#553f5d", bg = "#553f5d" }
marker_cut = { fg = "#553f5d", bg = "#553f5d" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#dabde2", bg = "#dabde2" }

# Count
count_copied = { fg = "#f7d8ff", bg = "#553f5d" }
count_cut = { fg = "#f7d8ff", bg = "#553f5d" }
count_selected = { fg = "#02315f", bg = "#dabde2" }

# Border
border_style  = { fg = "#a6c8ff" }

# : ]]]


# : Status [[[

[status]
separator_style = { bg = "#02315f", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#a6c8ff", fg = "#02315f", bold = true }
normal_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# Select mode
select_main = { bg = "#bdc7dc", fg = "#273141", bold = true }
select_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# Unset mode
unset_main = { bg = "#dabde2", fg = "#3d2846", bold = true }
unset_alt  = { bg = "#43474e", fg = "#c4c6cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a6c8ff", bg = "#111318" }
progress_error = { fg = "#ffb4ab", bg = "#111318" }

# Permissions
permissions_t = { fg = "#bdc7dc" }
permissions_w = { fg = "#dabde2" }
permissions_x = { fg = "#ffb4ab" }
permissions_r = { fg = "#553f5d" }
permissions_s = { fg = "#234776" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#a6c8ff" }
active = { fg = "#dabde2", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#a6c8ff" }
value = { fg = "#e1e2e9" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#a6c8ff", bold = true, bg = "#111318" }
inactive = { fg = "#bdc7dc", bg = "#111318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#a6c8ff", bg = "#02315f" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a6c8ff" }
title = {}
hovered = { fg = "#553f5d", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#111318" }
cand = { fg = "#a6c8ff" }
rest = { fg = "#02315f" }
desc = { fg = "#e1e2e9" }
separator = " â–¶ "
separator_style = { fg = "#e1e2e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e1e2e9" }
run = { fg = "#e1e2e9" }
footer = { fg = "#273141", bg = "#bdc7dc" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#dabde2" }
title_warn = { fg = "#a6c8ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e1e2e9" },
    { name = "*/", fg = "#a6c8ff" },
]

# : ]]]
